### ISSUE TITLE
Exception with IntelliJ 2023.2

### ISSUE THREAD

**Issue by FrankHossfeld** [coderazzi/aws_codeartifact_maven#9]
I got the following exception after upgrading to the latest IntelliJ version:

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at com.github.weisj.jsvg.aG.build(SourceFile:3121)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:115)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:109)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:36)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument$default(JSvgDocumentFactory.kt:34)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:30)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:291)
	at com.intellij.ui.svg.SvgKt.renderAndCache-rdQnj48(svg.kt:261)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache-rdQnj48(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvg-0e6sKCk(svg.kt:536)
	at com.intellij.ui.svg.SvgKt.loadSvg-0e6sKCk$default(svg.kt:78)
	at com.intellij.util.SVGLoader.load(SVGLoader.kt:46)
	at net.coderazzi.aws_codeartifact_maven.InputDialog.getIconPanel(InputDialog.java:337)
	at net.coderazzi.aws_codeartifact_maven.InputDialog.createCenterPanel(InputDialog.java:327)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1312)
	at net.coderazzi.aws_codeartifact_maven.InputDialog.init(InputDialog.java:264)
	at net.coderazzi.aws_codeartifact_maven.InputDialog.<init>(InputDialog.java:54)
	at net.coderazzi.aws_codeartifact_maven.LaunchAction.showDialog(LaunchAction.java:26)
	at net.coderazzi.aws_codeartifact_maven.LaunchAction.actionPerformed(LaunchAction.java:22)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$1(ActionMenuItem.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$2(ActionMenuItem.java:82)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

This happens right now after selecting Tools -> Generating AWS Code Credentials for Maven

**Comment by coderazzi** [comment]
Hi, Frank, thanks for letting me know it,
it seems that there is an issue with the usage of a SVG icon in the panel.
The idea library I use has been deprecated for long time, and I guess it
has changed underneath and broken my usage...
Best,
  Lu.

**Comment by FrankHossfeld** [comment]
Hi Lu.
hope you be able to fix it. The plugin is amazing and really useful ... 
cu Frank

**Comment by sfgvieira** [comment]
Ran into the same thing and came here to see if had been reported :)

**Comment by coderazzi** [comment]
Hi, I have uploaded a version to the stable and beta channels, but it takes
up to two days to get it approved...
This has been a quick patch, just disabling the load of the SVG icon, I
need a proper solution, but the plugin uses the Idea Plugin Devkit, which
causes many problems, and Idea just suggest to change the plugin to the Gradle
IntelliJ Plugin
<https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html>.
As soon as I change it, I will implement a correct workaround for the SVG
load and release a new version.
Thanks to both for reporting the bug!
 Lu.

**Comment by FrankHossfeld** [comment]
Thanks for the quick fix!
I'll updated the plugin to version 3.2.1 and now I got this exception:

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at com.github.weisj.jsvg.aG.build(SourceFile:3121)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:115)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:109)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:36)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument$default(JSvgDocumentFactory.kt:34)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:30)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:291)
	at com.intellij.ui.svg.SvgKt.renderAndCache-rdQnj48(svg.kt:261)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache-rdQnj48(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:590)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:274)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptor(imageCache.kt:249)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:124)
	at com.intellij.ui.icons.ImageDataByUrlLoader.loadImage(ImageDataByUrlLoader.kt:22)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:313)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:119)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1091)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.layoutCL(BasicLabelUI.java:108)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaLabelUI.layoutCL(DarculaLabelUI.java:94)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:262)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1721)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at java.desktop/javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:867)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/java.awt.Window.lambda$pack$1(Window.java:840)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2164)
	at java.desktop/java.awt.Window.pack(Window.java:832)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:682)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:468)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1643)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1657)
	at net.coderazzi.aws_codeartifact_maven.LaunchAction.showDialog(LaunchAction.java:27)
	at net.coderazzi.aws_codeartifact_maven.LaunchAction.actionPerformed(LaunchAction.java:22)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$1(ActionMenuItem.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$2(ActionMenuItem.java:82)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

which seams to be a new one.

**Comment by coderazzi** [comment]
Hi, Frank,
I tested the plugin using version 2023.2, without realizing that the test
spawns a IDE 2022.4 with the plugin installed, so basically, I just tested
that the solution was fine under 2022.4 :-(
I installed it now manually in 2023.2 and have the same error.
The problem lies in the internal handling of the SVG icon. Either there is
an error on the Idea classes (doubtful), or the Icon itself is wrong.
I will disable version 3.2.1. In the meantime, I tested version 3.2.0 and
that works fine.
Best,
 Lu.

**Comment by sfgvieira** [comment]
I gave it a try at solving the original issue (after I reported it) and I have created a fork with what seems to work on 2023.2
https://github.com/sfgvieira/aws_codeartifact_maven/commit/469da3b5a1bad23c5a9a9b796b6097a471bc7b86

The main changes (after converting it to gradle are):

![image](https://github.com/coderazzi/aws_codeartifact_maven/assets/39030072/1811f812-cefa-47e3-a0de-a1b8adafb4c8)

And on the original svgs (in META-INF) I set `width="140" height="140"` on both.

Perhaps you can give this a try and see if it helps.

Kind regards,
Sérgio

**Comment by coderazzi** [comment]
Thanks, Sergio, your change does indeed work!
I have uploaded it as version 3.2.2,
Best,
 Lu

**Comment by FrankHossfeld** [comment]
Hi Lu,
just installed the latest version and can confirm that it works again as expected. 
Thank you!
Frank
